{
 "title": "Multi-Instance User Resource Usage V2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "query": "p4d,p4de,p5,g5,r7,head,dgx" }
  ]
 },
 "panels": [
  {
   "title": "CPU 사용량 (시스템 전체)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\", mode!=\"idle\"}[1m]))"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}) by (instance)"
    }
   ]
  },
  {
   "title": "MEMORY 사용량 (시스템 전체)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemAvailable_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "GPU 사용자 현황", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GPU 상태",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=\"$instance\"}"
    },
    {
     "expr": "gpu_process_memory_mib{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "GPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort(DCGM_FI_DEV_GPU_UTIL{instance=\"$instance\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "CPU 사용자 현황", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "사용자별 CPU 코어 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (username) (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\", username=~\"aychoi|jykim|shlee|enhuh|hermee|srpark|bskim|hslee|hklee|ymbaek|hblee|shlee2|ybkim|jykim2|jwlee|yjgo|ckkang|sbkim|cgjang|yokim|syseo|sjchoe\"}[1m]))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  { "title": "Fsx 사용 현황 (AWS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "FSx 전체 사용량 (15.2TB / 16.8TB)",
   "type": "piechart",
   "description": "메타데이터 및 시스템 영역 1.6TB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheTimeout": "300",
     "expr": "fsx_lustre_bytes{type=\"used\"}",
     "legendFormat": "Used"
    },
    {
     "cacheTimeout": "300",
     "expr": "fsx_lustre_bytes{type=\"available\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "FSx /s3 전체 사용량",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "cacheTimeout": "300", "expr": "sum(fsx_s3_directory_bytes)", "legendFormat": "Total /fsx/s3 Usage" }
   ]
  },
  {
   "title": "FSx /s3 프로젝트별 사용량",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "cacheTimeout": "300", "expr": "fsx_s3_directory_bytes", "legendFormat": "/fsx/s3/{{directory}}" }
   ]
  }
 ]
}