global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 8760h
  receiver: 'sns-webhook'

receivers:
  - name: 'sns-webhook'
    webhook_configs:
      - url: 'http://sns-webhook:5001/webhook'
        send_resolved: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
